baseURL = "https://www.pathfinderscarpetcleaning.com/"
languageCode = "en-us"
[[menu.main]]
name = "FAQ"
url = "/faq"
weight = 6
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 7
[[menu.main]]
name = "Reviews"
url = "/reviews"
weight = 5
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Cities we Serve"
weight = 3
[[menu.main]]
name = "Services"
url = "/services"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
