baseURL = "http://example.org/"
languageCode = "en-us"
[[menu.main]]
name = "Cities we Serve"
weight = 2
[[menu.main]]
name = "Services"
url = "/services"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
