---
label: Services
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: featured_image
  type: file
  config:
    maxSize: 2
  label: Featured Image
- name: heading
  type: text
  config:
    required: false
  label: Heading
- name: subtitle
  type: text
  config:
    required: false
  label: Subtitle
- name: body
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: markdown
  label: Body
- name: seo
  type: include
  config: {}
  template: seo
  label: SEO
pages:
- content/services/air-duct-cleaning-air-quality.md
- content/services/carpet-upholstery.md
- content/services/pet-odors-stain-removal.md
- content/services/pressure-washing.md
- content/services/rug-cleaning.md
- content/services/tile-grout-cleaning.md
- content/services/water-damage-extraction-services.md
